
#ifdef USE_ADVANCED_CLASS
typedef enum {
	PCLASS_NONE,
	PCLASS_BFG,
	PCLASS_LIGHTNING,
	PCLASS_RAILGUN,
	PCLASS_LIGHTWEIGHT,
	PCLASS_HEAVYWEIGHT,
	PCLASS_RPG,
	PCLASS_SCOUT,
	PCLASS_GUARD,
	PCLASS_DOUBLER = PCLASS_HEAVYWEIGHT,
	PCLASS_AMMOREGEN = PCLASS_LIGHTWEIGHT,
	PCLASS_BARBARIAN,
	PCLASS_BARD,
	PCLASS_CLERIC,
	PCLASS_DRUID,
	PCLASS_FIGHTER,
	PCLASS_MONK,
	PCLASS_PALADIN,
	PCLASS_VISOR,
	PCLASS_RANGER,
	PCLASS_ROGUE,
	PCLASS_SORCERER,
	PCLASS_WARLOCK,
	PCLASS_WIZARD,
	PCLASS_FREEZE,
	PCLASS_ANTIGRAVITY,

	PCLASS_ROUND, // for ball physics

	// begin classes of monsters, not interested in item pickups
	PCLASS_MONSTER,
	PCLASS_SHAMBLER, // shambler
	PCLASS_DRAGON, // always flies because i lack animation ambition
	PCLASS_BERSERKER,
	PCLASS_GUNNER,
	PCLASS_VORE,

	PCLASS_MONSTER_COUNT,

	PCLASS_NUM_CLASSES
} pclass_t;
#endif

